### ISSUE TITLE
Ep 4 update challenge 4.3

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#100]
in https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio-Quarto/01-Project-Setup-Organization/02-good-project/index.html#challenge-43-relative-paths

The Challenge asks for reference to a file we do not have in the example repo `bronars.pdf`

need to update the challenge asking for reference to a file that does exist in the example repo.

![2023-11-13_720PM_scrnshot](https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/assets/275899/454dd632-b37f-4da3-8747-4aecbb9126dc)

**Comment by rcurty** [comment]
Changed example using data/raw/bronars_simulation_data.csv instead
