### ISSUE TITLE
Set up instructions

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#103]
FIXME Link to setup.html

**Comment by kristi-sara** [comment]
this is the setup.md file in our repo. I went to check out what was in the incubators setup but have to fix that one too. I removed the here package but there is still a reference to rticle and rprojroot unk if we need these or if its a remnant of old quarto

**Comment by kristi-sara** [comment]
https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio-Quarto/setup.html is linked. I will close this issue.
