### ISSUE TITLE
Review Content - Getting Fancy with Code Chunks

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#108]
Review/Revise 

From Run Code from an external script in a code chunk onwards

https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio-Quarto/02-Quarto/05-code-chunks/index.html

**Comment by torwhite** [comment]
started reviewing, but #109 should be discussed before further changes.

**Comment by brunj7** [comment]
👀

**Comment by rcurty** [comment]
Julien updated project yml mentions and also added the file to the project example repo https://github.com/UCSBCarpentry/Quarto-Project-Example/commit/230fe171455d1f6da1b2a3da2d2516bcf53e4bc6

**Comment by rcurty** [comment]
closing this for now. we will need a last pass once #109 reorg is completed to check for flow.
