### ISSUE TITLE
Remove references to RMarkdown backward compatibility?

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#110]
as reference in https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio-Quarto/02-Quarto/05-code-chunks/index.html#note-r-markdown-method-for-setting-working-directory-also-works-in-quarto 

and https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio-Quarto/02-Quarto/05-code-chunks/index.html#tip-overiding-global-options)

Also relevant to #91

**Comment by ilessing** [comment]
Agree we should remove RMarkdown backward compatibility instructions/discussion.

Goal of this workshop is to introduce learners to Quarto & RStudio as they are now.   Providing guidance to those who may have experience with previous versions should be _out of scope_ of this workshop.     Instruction about earlier versions and methods is likely to confuse those who are encountering RStudio/Quarto for the first time.

**Comment by rcurty** [comment]
done
