### ISSUE TITLE
consider teaching Github Auth using the `usethis` package

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#113]
For Episode 10 [Collaborating via Github – Introduction to Reproducible Publications with RStudio](https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio-Quarto/03-Collaboration/01-github/index.html)

The "UseThis" R package reputably eases creation and use of Github Personal Access Tokens (PAT) within RStudio/Quarto

- [Automate Package and Project Setup • usethis](https://usethis.r-lib.org/)
- [Coverage in the MEDs workshop](https://ucsb-meds.github.io/meds-install-mac.html#store-your-github-personal-access-token-pat)
- [About authentication to GitHub - GitHub Docs](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github)

Q: Could _UseThis_ work for learners in the context of Collaboration episode of the workshop?

relates to #43

**Comment by ilessing** [comment]
see also: [Designing a Reproducible and Collaborative Lab (RCL) - Using git and GitHub with RStudio](https://ucsb-library-research-data-services.github.io/reproducible-lab/git_rstudio.html#using-r)

**Comment by ilessing** [comment]
```r
install.packages("usethis")
usethis::create_github_token()
gitcreds::gitcreds_set()
usethis::git_sitrep()
```

above works well locally.


Need to test on JupyterHub!!

**Comment by brunj7** [comment]
this is the command we use on Linux servers that do not cache the token automatically: 

```bash
git config --global credential.helper 'cache --timeout=10000000'
```

`timeout` is in seconds

**Comment by ilessing** [comment]
results of testing with JupyterHub (LSIT provided instance)

- when I open a new RStudio project and look at the packages pane I see the `usethis` package listed.
```R
packageVersion('usethis') 
[1] ‘2.2.2’
```

**Comment by ilessing** [comment]
another documentation link:  https://usethis.r-lib.org/articles/articles/git-credentials.html

**Comment by rcurty** [comment]
done
