### ISSUE TITLE
Fix output path in lesson `Adding Code-Generated Plots and Figures`

### ISSUE THREAD

**Issue by brunj7** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#118]
I fixed the Rscript path to match the new file structure  but forgot to update the code in the lesson

https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio-Quarto/02-Quarto/04-plots-figures/index.html

**Comment by rcurty** [comment]
Should be https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio-Quarto/02-Quarto/05-code-qmd/index.html

**Comment by ilessing** [comment]
2cf8727ee493
