### ISSUE TITLE
Challenge 4 in Bibliography, Citations & Cross-Referencing 

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#119]
Need to change the figure used in this challenge.

Using a different figure means success in this challenge will not depend on success in earlier episode challenge.

![Challenge4-bib-and-cross-ref](https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/assets/275899/0ed06ab2-0a8b-41a8-b7e4-fe583892c192)

**Comment by rcurty** [comment]
Rewrote the challenge in a more simple way. Even if learners have not completed the previous challenge, they will be able to catch up quickly.
