### ISSUE TITLE
Broken Figs GitHub Ep.

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#127]
https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio-Quarto/03-Collaboration/01-github/index.html

**Comment by ilessing** [comment]
This is a file name case sensitivity issue.

`10-GitHub-new-PAT-options.png`

-- vs --

`10-github-new-PAT-options.png`
![](https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/blob/review-revise/fig/10-github-new-PAT-options.png)
