### ISSUE TITLE
Ep. 3 - Investigate issue with journal format

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#13]
Journal format demo not rendering correctly.
See: https://stackoverflow.com/questions/73216317/fail-to-replicate-quarto-elsevier-template

**Comment by ilessing** [comment]
@ilessing to help with this.

**Comment by rcurty** [comment]
https://quarto.org/docs/journals/formats.html

**Comment by ilessing** [comment]
issue crops up at the end of [episode 3](https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio-Quarto/03-quarto-documents/index.html#creating-pre-formatted-papers)

**Comment by rcurty** [comment]
journal templates require features in Quarto 1.2 [pre-release versions of Quarto](https://quarto.org/docs/download/prerelease.html). After install, follow instructions: https://github.com/quarto-journals/elsevier#format-options

**Comment by rcurty** [comment]
I will add that part of the content to ep. 3
