### ISSUE TITLE
12/11/23 Day 1 workshop. Quotes missing in code chunk 

### ISSUE THREAD

**Issue by kristi-sara** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#130]
I can't remember which episode, but one of the code chunks we run for a challenge or lesson  runs on a loop since the end quote is missing.  session needs to be restarted to break the loop.

**Comment by rcurty** [comment]
Not a challenge. I took notes that there was a parenthesis for the code below, but it seems ok?

`install.packages(c("bookdown", "tidyverse", "BayesFactor", "patchwork","usethis"))`

https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/edit/review-revise/_episodes/02-Quarto/01-basic-rstudio.md

**Comment by rcurty** [comment]
https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/commit/c5ce3e3c9c02eecf243e71e311b843fd72561f52
