### ISSUE TITLE
Figs renumbering

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#132]
We removed fig. 2 for simplicity, but for the code-generated plots, we start in 3.

**Comment by rcurty** [comment]
Fig. 3 should be 2, and Fig.4 becomes Fig. 3. Change all references.

**Comment by ilessing** [comment]
reviewed together today and this is still needed.

**Comment by torwhite** [comment]
Will need to redo a screenshot in "Adding Code to Quarto Documents" at the very least. May be a couple other references in that episode where Fig 3 needs to be changed to Fig 2.

**Comment by ilessing** [comment]
need to update :
[`/fig/07-run-from-chunk.png`](https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/blob/main/fig/07-run-from-chunk.png)

**Comment by ilessing** [comment]
reviewed with Renata and we think we got this all fixed.  closing
