### ISSUE TITLE
Fig. chunk labels and captions

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#134]
If we add numbers fig3-, fig4- this will affect the ability for cross reference. Better to keep numbers only for caption.

**Comment by rcurty** [comment]
removed numbers from code chunk lables. See: https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/commit/36ba58c92f9314ce9bf9b0f4350982d2da88aad5

**Comment by rcurty** [comment]
I think this can be closed.

**Comment by torwhite** [comment]
Looks good - closing.
