### ISSUE TITLE
YAML file missing from screenshot

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#135]
https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/blob/review-revise/_episodes/01-Project-Setup-Organization/02-good-project.md

**Comment by ilessing** [comment]
figure:

![04-directory-tree.png](https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio-Quarto/fig/04-directory-tree.png)

**Comment by ilessing** [comment]
procedure for creating the figure is outlined/documented in #14

**Comment by ilessing** [comment]
fixed with commit: d115dfec
