### ISSUE TITLE
YAML explanation

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#136]
We have a brief intro about the YAML here https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/blob/review-revise/_episodes/02-Quarto/03-quarto-documents.md
But we do not even mention the project level yaml until the path correction later https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/blob/review-revise/_episodes/02-Quarto/05-code-qmd.md
Perhaps move the execute-dir content at the end of 05-code to advanced code chunk ep.

**Comment by rcurty** [comment]
Add an intro to Quarto projects so learners will know about the default files, including the project level YAML. Create a project and then use the qmd for the first qmd. 

See #15 - Add the screenshot to  https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/blob/review-revise/_episodes/02-Quarto/03-quarto-documents.md

**Comment by rcurty** [comment]
Add a callout to Ep. https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/blob/review-revise/_episodes/02-Quarto/03-quarto-documents.md including information about the project .yml. 
Add to Ep. https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/blob/review-revise/_episodes/02-Quarto/07-advanced-chunk.md we will touch on that (add call back)

**Comment by rcurty** [comment]
suggested blurb/callout: 

A note about Quarto projects: 

Quarto projects enable efficient rendering of files in a directory, support shared YAML configuration across documents, and provide the flexibility to redirect outputs to a specified directory. All Quarto projects include a _quarto.yml configuration file so that any document rendered within the project directory will automatically inherit the metadata defined at the project level. 
Because we are just getting started with Quarto, let’s get to the basics first, and later, we will explore some advanced things we can accomplish with projects.

**Comment by torwhite** [comment]
Would the callout be added to episode 5? Again, I think this makes sense with the natural flow of teaching - I ended up talking about Quarto projects after the execute-dir change. 

The execute-dir part could be changed to the episode on Advanced code chunk options, but it MUST be addressed before external code. I think it works as it is in ep. 5 as long as we include that callout about Quarto projects.

**Comment by rcurty** [comment]
Update the screenshot when we ask learners to create a new project from version control.

**Comment by torwhite** [comment]
As part of this issue I will move the content from ep. 5 to 7 and adding an explanation of Quarto projects to ep. 7 (Advanced Code chunks)

**Comment by torwhite** [comment]
Added YAML explanation to ep. 7 along with the content move from ep. 5 to 7. Please review

**Comment by rcurty** [comment]
All good.
