### ISSUE TITLE
Add custom code global execution 

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#137]
Fixing the output at the code chunk level can be demonstrated once and then, move to the yaml as a global change.

**Comment by rcurty** [comment]
07-advanced-code-chunks
Remove tip and add content?
> ## Tip: YAML code chunk options
> We can also tweak some code chunk settings at the project level in the `_quarto.yml` file which changes how code chunks are displayed for the entire project. We're not going to get into this in the workshop, but many of the same options you set in your global code chunk settings are also configurable in the `_quarto.yml` YAML. 
{: .callout}

**Comment by torwhite** [comment]
Perhaps this can be added to the advanced options episode? We certainly have the time during that episode because we really only cover running external code (assuming the code chunk best practices for loading packages/data gets moved to the previous episode)

**Comment by torwhite** [comment]
Decided in #136 that we will move the execute-dir content to Advanced code chunks - that will give a good transition to talk about other global yaml options.

**Comment by torwhite** [comment]
Added the reorg with a FIXME note to add another example for global "_quarto.yml" options

**Comment by rcurty** [comment]
all good
