### ISSUE TITLE
Ep 02-Quarto/06-rendering-code

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#138]
Before the inline code exercise learners have to load Tidyverse. 

https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/blob/review-revise/_episodes/02-Quarto/06-rendering-code-yaml.md

**Comment by rcurty** [comment]
If we cover best practices for loading packages at the top of the document before introducing inline code, this will be resolved. We load packages as part of the code chunks which are presented further down in the paper.

**Comment by torwhite** [comment]
Agree. It was more natural to teach by covering best practices for loading packages/data before (or during ) the section on inline code. I also propose it be moved from Advanced options episode to the Rendering code episode.

**Comment by rcurty** [comment]
@torwhite can you please review and close it?

**Comment by ilessing** [comment]
> @torwhite can you please review and close it?

4d36fc0113 Changes  can be seen at: https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio-Quarto/02-Quarto/06-rendering-code-yaml/index.html#best-practices-for-loading-data-and-packages

**Comment by torwhite** [comment]
I like the added challenge. The flow could be improved a bit, but I don't think it prevents us from moving forward and closing the issue.
