### ISSUE TITLE
Add more challenging challenges

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#139]
Depending on the audience, the challenges we have might be too basic. Having more advanced content or complex episodes will help accommodate different proficiency levels.

**Comment by gjanee** [comment]
Publish via push to gh-pages branch (ultimately this is probably a better way to publish via GitHub)

**Comment by gjanee** [comment]
Renv: construct scenario in which learners receive project with older dependencies, do restore to install older versions, but also, upgrade to newer versions and then do a new snapshot.  That would represent a full cycle of using Renv.

**Comment by gjanee** [comment]
Present strategies for presenting/publishing writeup and code that does long-running computation.  (I.e., if a workbook takes 8hrs to run, how might it be arranged to allow somebody to revisit it without having to rerun it up front, if that makes sense)

**Comment by gjanee** [comment]
I think this might already be in the lesson, but include info on project-wide paths so that one can do work directly on and run code files, and also render Quarto documents, without futzing with relative paths

**Comment by rcurty** [comment]
> Present strategies for presenting/publishing writeup and code that does long-running computation. (I.e., if a workbook takes 8hrs to run, how might it be arranged to allow somebody to revisit it without having to rerun it up front, if that makes sense)

We will add a callout about this with a link for further exploration.

**Comment by rcurty** [comment]
> Renv: construct scenario in which learners receive project with older dependencies, do restore to install older versions, but also, upgrade to newer versions and then do a new snapshot. That would represent a full cycle of using Renv.

We will include this as an issue for contributors.

**Comment by rcurty** [comment]
> I think this might already be in the lesson, but include info on project-wide paths so that one can do work directly on and run code files, and also render Quarto documents, without futzing with relative paths

this is already in the lesson

**Comment by rcurty** [comment]
> Publish via push to gh-pages branch (ultimately this is probably a better way to publish via GitHub)

We will add this issue asking for contributions, so we can push it to the incubator asap.
