### ISSUE TITLE
Ep. 4 File Directory Image

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#14]
Ep. 4 first image - line 117

Ian, do you remember what you used to create this file directory screenshot? I don't recall anymore

**Comment by ilessing** [comment]
I used command line tool `tree` to make the list and then screenshot it on my Mac.  command-shift-4

I'm happy to make a new one.

![04-directory-tree.png](https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/blob/2d72627bfc601869c0681e7b73b4ce35d71354e5/fig/04-directory-tree.png)  

https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/blob/2d72627bfc601869c0681e7b73b4ce35d71354e5/fig/04-directory-tree.png

**Comment by ilessing** [comment]
correction... 
I did not use Mac screenshoting.  Instead I used https://carbon.now.sh/
with the "One Light" theme.


produced the tree listing with:
`tree  > 04-directory-tree.txt`

then hand edited the file `04-directory-tree.txt` so it wasn't so crazy long and replaced invis chars `<0xa0><0xa0>` with two spaces.  The I cut and pasted text into carbon.now.sh and exported to PNG.  Then renamed and resized the PNG.  

- Width: 572px

**Comment by ilessing** [comment]
By the way...

if you want the `tree` command line tool just brew install it:

`brew install tree`

**Comment by ilessing** [comment]
fixed with: 5b6ba966c6765

**Comment by ilessing** [comment]
need to remove outdated files and then re-do the dir listing figure

**Comment by torwhite** [comment]
Thanks Ian. Due to some oddities with Quarto, I might have to change the directory sturcture a bit. I'll let you know when that is done and when the files are deleted.

**Comment by ilessing** [comment]
![Screen-Shot-2022-10-04-at-7 08 58-PM](https://user-images.githubusercontent.com/275899/194139312-de94fd37-e59d-4229-b248-a3bcf5b605b5.png)

**Comment by ilessing** [comment]
@torwhite said ready for a new directory tree figure.

> torwhite in slack October 21st at 9:12 AM  
>  I’ll clean up the files in the project example, and maybe after the meeting we’ll be ready to talk that directory screenshot. 
> Just want to clarify these things with renv first. So if you have time to look into renv a bit that would be nice.

**Comment by ilessing** [comment]
@rcurty  This is the issue that mentions `tree`     install it with `brew install tree`

**Comment by ilessing** [comment]
see also #90 

and issue 7 in the project example repo: https://github.com/UCSBCarpentry/Quarto-Project-Example/issues/7
