### ISSUE TITLE
Redo Screenshot

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#141]
https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/blob/review-revise/fig/08-HR-external-code.png

this should be updated without all the non-required  , local=knitr...

**Comment by ilessing** [comment]
I think this issue is similar to #131 which was fixed with commit: aa5d09ab447cd9

**Comment by rcurty** [comment]
done
https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/commit/36cfd0a88eae8f42393d74dd42574f2662592b77
