### ISSUE TITLE
Review & Edit Setup instructions

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#142]
I walked through the setup instructions for the R-ladies workshop, reinstalling RStudio and R. 

1) Installing the standalone Quarto CLI is no longer necessary now that it is integrated into RStudio. 

2) I don't believe we use the bookdown package in the workshop (and to my understanding those features are integrated into Quarto) so the package does not need to be loaded.
3) I had to install the rmarkdown package to create a .qmd document.

**Comment by kristi-sara** [comment]
1. removed reference to install quarto cli, did keep a you may need to (and how to check if you have it) 
2. removed bookdown package, replaced with rmarkdown package
