### ISSUE TITLE
Suggestion to rename Modules

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#149]
Module 1 - Reproducibility and Project Organization (repro-project-org)
ep. 1: reproducibility
Module 2 - Quarto/RStudio (quarto)
Module 3 - Collaboration (collaboration)

**Comment by ilessing** [comment]
These seem like good Module names.   I take it we would be changing the sub-directory names under `_episodes`


| Module | current name               | proposed                                            | slug / directory               |
|--------|----------------------------|-----------------------------------------------------|---------------------|
| 1      | Project Setup Organization | Module 1 - Reproducibility and Project Organization | `01_repro-project-org` |
| 2      | Quarto                     | Module 2 - Quarto/RStudio                           | `02_quarto`            |
| 3      | Collaboration              | Module 3 - Collaboration                            | `03_collaboration`     |

@torwhite @brunj7 @kristi-sara What do you think?

**Comment by rcurty** [comment]
renamed files accordingly
