### ISSUE TITLE
Ep. 4 Add information about Quarto Project

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#15]
Should Quarto projects be introduced here? Or in Ep.8 when the _quarto.yml file is needed. 

A Quarto project is just a .Rproj with a _quarto.yml file included.

**Comment by brunj7** [comment]
We discussed this with @rcurty and I am adding the `_quarto.yml` file to the Quarto-Project-Example
repo as in getting fancy with code chunk it seems to assume that the file already exists

**Comment by brunj7** [comment]
OK done: https://github.com/UCSBCarpentry/Quarto-Project-Example/commit/230fe171455d1f6da1b2a3da2d2516bcf53e4bc6
