### ISSUE TITLE
Ep.6: More text and formatting options with Quarto

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#17]
Unlike r markdown, Quarto allows html styling at the block level and inline. 

Pretty cool options for layouts too (i.e. columns) with "fencing"
perhaps this could be added to ep. 6

**Comment by rcurty** [comment]
https://quarto.org/docs/authoring/markdown-basics.html#divs-and-spans
https://quarto.org/docs/authoring/tables.html#grid-tables
https://www.rstudio.com/blog/6-productivity-hacks-for-quarto/

**Comment by rcurty** [comment]
Adding some examples from here
https://r-craft.org/r-news/6-productivity-hacks-for-quarto/
Many cool videos with styling and fonts, I might create a list for learners (and us) for future reference.
