### ISSUE TITLE
 Episode 5 git config step needed when running Rstudio in Jupyter Hub or git config not yet set

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#22]
Grace tried to connect with git and its running into this issue

<img width="806" alt="screenshot_2022-10-21_163030" src="https://user-images.githubusercontent.com/275899/197305723-381c8aad-97c4-488b-bed1-903c30eed713.png">

- [Episode 5 - Your First Edit](https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio-Quarto/05-setup-versioning/index.html#your-first-edit)

**Comment by rcurty** [comment]
Hey @ilessing Ian, can I assign this to you?
