### ISSUE TITLE
Setup and JupyterHub Quarto Version

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#23]
The native quarto built-in in Rstudio does not render journal templates/formats correctly. We need to include that in the setup and ensure the required version is running on the jupyterlab instance 

These templates require features in Quarto 1.2, so you will currently need [pre-release versions of Quarto](https://quarto.org/docs/download/prerelease.html).

**Comment by ilessing** [comment]
I think you mean Jupyter Hub that LSIT provides: https://carpentryworkshop.lsit.ucsb.edu/

@kristi-sara  If so maybe we can ask LSIT to upgrade to Quarto 1.2

**Comment by kristi-sara** [comment]
Ok. We're in the middle of the R data viz workshop and they're looking into Docker not pulling the image (ugh) so they can fix this while they are at it.

**Comment by ilessing** [comment]
I checked Jupyter Hub and it has Quarto 1.0.36 installed.  We need Quarto 1.2 to be compatible with Quarto Journal Templates.

```
jovyan@jupyter-ianless:~$ date; quarto --version
Tue Oct 25 06:52:16 PM UTC 2022
1.0.36
```

**Comment by kristi-sara** [comment]
Haven't heard back from jupyterhub people yet. I'll pester after the data viz workshop

**Comment by ilessing** [comment]
@kristi-sara thanks.  No hurry.  Just a low priority thing for later.  I'll assign this issue to you for now.

**Comment by ilessing** [comment]
LSIT updated the version of Quarto on Jupyter Hub but _not_ to 1.2+ which is the version we need for the Journal Templates.

| date   | quarto version on LSIT JupyterHub |
| ------ | -------------- |
| Oct 25 | 1.0.36         |
| Nov 1  | 1.1.189        |

@kristi-sara Can you ask LSIT to install the latest "release candidate" version for us?

https://quarto.org/docs/download/

Currently the Linux version we would like installed on JupyterHub is  **1.2.256**

**Comment by ilessing** [comment]
see also: #5

**Comment by rcurty** [comment]
> packageVersion("quarto")
[1] ‘1.2’
Connected to your session in progress, last started 2022-Nov-02 17:06:54 UTC (1 hour ago)
