### ISSUE TITLE
Ep.4 & Ep. 8 - Reconsider Renv

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#29]
Ep. 4 Introduces Renv and mentions that the content will be covered in more detail ep. 8. Considering Greg's comments, should we remove that reference?

**Comment by rcurty** [comment]
See #21

**Comment by kristi-sara** [comment]
<img width="508" alt="is that what this is" src="https://user-images.githubusercontent.com/48770663/199816031-a11d654d-b37c-4401-a47f-82a5041942c5.PNG">

when I forked rstudio-example to my repo and then cloned it into juptyer-Rstudio, it threw this thing out about the Renv()

**Comment by ilessing** [comment]
closing after Greg's recent update to episode 8
