### ISSUE TITLE
Ep. 5 - No source folder

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#30]
Remove references and screenshots showing the qmd in the report/source folder.

**Comment by rcurty** [comment]
Ep. 4 (list of best practices), ep. 5 screenshots and mention.

**Comment by ilessing** [comment]
after discussion in meeting today we decided that we will NOT have a `source/` folder inside the `report/` folder.

We'll need to adjust lessons (screenshots and text) to reflect that change.

**Comment by rcurty** [comment]
Removed source folder references in ep. 4 and 5.
pushed new figs without the reference to the source folder ep. 5
