### ISSUE TITLE
Episode 7: Renv in code chunks

### ISSUE THREAD

**Issue by kristi-sara** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#39]
I don't think this is working for us. Too many learners have had to reinstall or restore packages after renv forcefully removes them and its slowing us down.

**Comment by rcurty** [comment]
We should cover the (renv::restore) in episode 7 instead

**Comment by kristi-sara** [comment]
Possible work around is not installing any packages and using the renv to restore when we get to that point in the lesson? per kristi, selective-git curse

**Comment by kristi-sara** [comment]
https://git-scm.com/docs/gitcredentials

**Comment by rcurty** [comment]
Addressed in issue #57.
