### ISSUE TITLE
Episode 7: Heart Rate Figure/Plot

### ISSUE THREAD

**Issue by kristi-sara** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#40]
There is an additional (or was it missing) space in the code: 

echo: false
message: false
warning: false
results: false

And its not specific enough which code chunk is supposed to be copied from 03-HR-Analysis.R, some students were copying only partial code instead of the whole thing. There appears to be a path issue that is also causing hiccups, after we throw the code into the qmd file. Having an untitled, unsaved document is screwing with the lesson.

**Comment by kristi-sara** [comment]
something about the #| echo:false 

I missed that part helping a learner

**Comment by rcurty** [comment]
There was a typo when that was taught...learners that got to that point were able to get it working when we corrected it. But will be less confusing if the challenge follows the quarto structure instead of {r .......}

**Comment by torwhite** [comment]
Add to instructor notes: 

- there SHOULD be an error
- we will fix error 
- in Ep 8 will discuss a more reproducible way to deal with relative paths in R projects

**Comment by torwhite** [comment]
Redo this screenshot: 07-heartrate-code.PNG

**Comment by torwhite** [comment]
I added the code to the episode itself to make it easier to follow. Now, this only helps if the learners also have the lesson open so they still may need to navigate to the episode example to copy and paste the code. 

I will propose a re-organization of the code episodes to make this relative path error ---> fix less confusing and more concise.

**Comment by rcurty** [comment]
We can't seem to find this figure in the code eps. Not even the earlier versions before the reorg.

**Comment by rcurty** [comment]
Figure is no longer part of the episode, only code.
