### ISSUE TITLE
In general R console vs R terminal

### ISSUE THREAD

**Issue by kristi-sara** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#41]
Some learners don’t understand the distinction between the console and the terminal. We didn't press too much in the prereqs but maybe next time we should say prereqs are rstudio and Unix Shell.

**Comment by rcurty** [comment]
Introduce that difference in the ep. getting around in rstudio. Emphasize the differences in use.

**Comment by rcurty** [comment]
During Episode 2, it might need to be clarified to all learners the distinction between the console and the terminal. So, we recommend that instructors cover this difference: "using the console, you submit commands to and interact with R through RStudio; whereas the terminal provides command line access to the computer's operating system".
