### ISSUE TITLE
Ep. 4 - Introduce and cover renv

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#44]
The renv portion isn't covered until ep. 8, but there is a dependency in ep. 7 that can cause some problems. It could be introduced early on in ep. 4, when we present the project folder.

**Comment by torwhite** [comment]
Leave as a short callout in reference to project best practices, but renv won't be discussed fully until ep. 10.

**Comment by rcurty** [comment]
#57 will address this issue. Learners won't engage with renv until before the publishing ep.
