### ISSUE TITLE
Ep. 7 - Simplify

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#48]
Rewrite inserted code chunk (03_HR_analysis.R) to not take so much time, and not spit out intermediate output, just the plot at the end.  30-60s to render is way too long for a class.   We can still have the code read in a data file if you want to understand/practice relative pathname fixups.

Make it clearer that the first code chunk insertion in the test document is just a test by not inserting 03_HR_analysis.R but just some small snippet of code that creates a simple plot.

**Comment by rcurty** [comment]
Relates to Issues #50 and #48.

**Comment by gjanee** [comment]
Is this issue still open?  I created a simplified version of the example code, but don't have permission to push to the example repo.  But then, already dealt with?

**Comment by rcurty** [comment]
Yes, this issue is open. @torwhite is still working on it. I have granted you access to the project example repo https://github.com/UCSBCarpentry/Quarto-Project-Example so you can push your contribution.

**Comment by torwhite** [comment]
Hi @gjanee we clarified last Friday that it's not the code that is the biggest issue in rendering time but that the paper was too long. We tested with the short paper and the rendering time was much better. 

It may be that it is still helpful to have the simplified code, but could you add it to a separate branch or do a pull request? As Renata said, I am working on this right now and I want to test first before pushing to main branch. 

Thanks

**Comment by gjanee** [comment]
Sounds like I should wait, if this is needed at all.  What I did was write the data frame out to a CSV file, then replace the code with code that just reads in the CSV and plots it.

**Comment by torwhite** [comment]
per comment in #62 we simplified the paper which means we no longer need the blank qmd to cut down on render time. Just pushed changes to main branch to remove the part where we open a blank qmd doc to test code.
