### ISSUE TITLE
Ep. 7 - Add simpler inline code chunk

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#49]
Do a simple insertion of an inline code chunk in the test document so students can see more clearly what's happening. We can still do more complicated inline code in the actual document, but it will help if students have already seen it.

**Comment by torwhite** [comment]
clarified that the teaching flow should be simpler not the inline code itself.

**Comment by torwhite** [comment]
see #62 for simpler teaching flow
