### ISSUE TITLE
Setup - RStudio (v2022.07) or later

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#5]
Update version

**Comment by ilessing** [comment]
today (2022-11-01) when I checked versions in the [Jupyter Hub](https://carpentryworkshop.lsit.ucsb.edu/) system which we're planning to use next week I got:

```
- Using R 4.2.1 (lockfile was generated with R 4.1.3)
   nickname       Funny-Looking Kid

- RStudio 2022.07.2+576 "Spotted Wakerobin" 
   Release (e7373ef832b49b2a9b88162cfe7eac5f22c40b34, 2022-09-06) for Ubuntu Bionic

- quarto --version
    1.1.189
```

@rcurty Do we still need to add something about this to 'setup.html' ??

**Comment by ilessing** [comment]
see also #23

**Comment by rcurty** [comment]
ran a 
> packageVersion("quarto")
[1] ‘1.2’

So we should be good to go. Starting a run-through on Jupyter Hub.

**Comment by ilessing** [comment]
on JupyterHub environment after doing what was probably an un-necessary package install I now get this In the RStudio console:

```
> date() [1] "Wed Nov  2 19:07:38 2022"
> packageVersion("quarto") [1] ‘1.2’
```

So... Yeah I think we have the needed version of Quarto on JupyterHub.
