### ISSUE TITLE
Ep. 3 - PDF output note

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#52]
PDF support was very tricky in my experience, e.g. requires understanding of shell paths, more guidance required.

**Comment by rcurty** [comment]
add to teaching notes.

**Comment by kristi-sara** [comment]
What was the issue with tinytex again? Sam and Kat asked if the pdf output was rocky but after some hiccups it spit out a pdf right?

**Comment by rcurty** [comment]
Added to the teaching notes:
During Episode 3, when the option to produce pdf outputs using TinyTex is presented, instructors should clarify that it requires extra installation that is separate from the lesson. Instructors may choose to demonstrate the PDF on the side. If you choose so, please make sure to install TinyTex following the same approach you used to install quarto (command line vs. console). If you installed quarto through the RStudio IDE, then quarto will only be on your path if you run the integrated RStudio IDE terminal.
