### ISSUE TITLE
Ep. 8 - RENV

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#53]
renv: Suggest not starting with renv configured; instead, have learners initialize it themselves, that's the more common thing they would do anyway. Can still talk about restoring of course.

**Comment by ilessing** [comment]
We're considering excluding `renv` from workshop as it is a more advanced topic and some encountered package issues when using 'renv'

as a compromise it might be best to include `renv` section at the end of the workshop.

**Comment by gjanee** [comment]
renv use is vastly simplified if all students do is an renv::init()

**Comment by rcurty** [comment]
Renv file has been removed.
