### ISSUE TITLE
RENV - specify minimum version but not maximum

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#54]
Is is possible using the `renv` system to specify a minimum package version but not a maximum version number.

This is possible with other packaging systems such as composer (PHP) and NPM (Javascript).

The goal would be to allow advanced learners with newer versions of any of the required packages to use the RENV system without rolling back any of their package versions to earlier ones.

**Comment by joelnitta** [comment]
AFAIK this is not possible with renv - I don't think it is set up to work that way.

But it is possible with another approach (courtesy of @jennybc), using a `DESCRIPTION` file.

Basically, if you have a `DESCRIPTION` file that includes minimum package versions specified under `Imports`, you can use `pak::local_install_deps()` to install all of those packages at at least the minimum version.

Here is an example with some of the packages used in the example project:

```
Package: rpkgs
Title: R Packages
Version: 0.1
Authors@R: 
    person("Joel", "Nitta", role = c("aut", "cre"))
Description: Use this file to specify required packages and minimum versions
Imports:
    tidyverse,
    stringi (>= 1.7.8),
    BayesFactor (>=0.9.12),
    patchwork
Encoding: UTF-8
```

Try saving that as `DESCRIPTION` (no file extension) in an R project, then open the project and run `pak::local_install_deps()`.

Of course this would have implications for how to teach renv...

**Comment by joelnitta** [comment]
Also...

> The goal would be to allow advanced learners with newer versions of any of the required packages to use the RENV system without rolling back any of their package versions to earlier ones.

renv doesn't affect the user-level library; it installs package on a per-project basis. So it would not affect any of the packages the user already has installed in other projects or outside of renv.

**Comment by torwhite** [comment]
With new format for teaching renv, this issue is no longer relevant.
