### ISSUE TITLE
Episode 5: Your turn! 

### ISSUE THREAD

**Issue by kristi-sara** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#55]
https://carpentries-incubator.github.io/Reproducible-Publications-with-RStudio/05-setup-versioning/index.html

What was supposed to be in this code box? It just says code.... Sorry I'm not sure why I didn't add this earlier

**Comment by ilessing** [comment]
![Screen-Shot-2022-12-12](https://user-images.githubusercontent.com/275899/207092774-a423fa93-0a21-4fbe-8efc-209102ebf9e8.png)

**Comment by rcurty** [comment]
This problem remains in the outdated version in the incubator, but we'll have to sync all the updates anyways.  We already fixed this; we may have forgotten to close it. Closing it now.

**Comment by rcurty** [comment]
Forgot we are keeping the rmd version in the incubator and submitting a different lesson for quarto. So I will fix that box in the incubator version and close it here when completed.

**Comment by rcurty** [comment]
Done - 40f05d7b1a677bb92979a14698c52c9d8d8c85c9
