### ISSUE TITLE
Shrink size of example?

### ISSUE THREAD

**Issue by joelnitta** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#56]
The [example project](https://github.com/carpentries-incubator/Reproducible-Publications-with-RStudio-Example) includes a lot of code (7 R scripts) and packages (109 by my count) and a lot of content in the Qmd file, but not all of it gets used in the workshop (only two chunks get added from the scripts). There are some disadvantages to this:
- It takes a long time to install (restore) all the packages with renv, especially if the participants haven't used them before.
- There is a greater chance of not being able to install some random package, and then renv just stops trying to restore.
- There is a lot of material to scroll through when browsing the Qmd.
- It places unnecessary mental load on the learners to keep track of all of this content.

I can see the advantage is perhaps that the code is a bit more realistic, and something like what they might encounter in the "real world". But I think drastically cutting it back could help workshops run more smoothly (less install errors) and make for a friendlier learning environment (less stuff to keep track of).

**Comment by ilessing** [comment]
@joelnitta Thank You for your detailed comments and help with this.  We are in agreement. 

We discussed this our team today and agreed to:

- pare down example to what is needed for hands on activity in the workshop
    -   remove unused files (data & code)
    - pare down the paper itself to include only relevant examples that are covered in the workshop (code chunks and markdown)
- in Episode 4 we will show the full folder structure "as an example" of real world project
- In introduction link the full data paper

**Comment by ilessing** [comment]
as of our 2023-01-27 working meeting Renata has reduced size and complexity of the example project.  
Those changes will be finalized soon.    
see: [Quarto-Project-Example](https://github.com/UCSBCarpentry/Quarto-Project-Example) repo.

Also we've decided not to use `renv` functionality to do initial package installation.  Rather during the workshop there will be an episode where we explain use of `renv` and guide learners in creating an `renv` file.

**Comment by rcurty** [comment]
Example was simplified and unecessary files were removed.
