### ISSUE TITLE
Fix example repo link 

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#60]
points to the old quarto branch. Point to https://github.com/UCSBCarpentry/Quarto-Project-Example instead.

**Comment by rcurty** [comment]
done, but once we move it to the incubator we might have to update that again.

**Comment by rcurty** [comment]
In episode 4 
remove /code/04-07 can be removed
data/  GARP-TEST mastersheet.xls ← retain
data/ bronars_sim ← retain
data/  removed all the other files in /data/
output/data/  keep
output/plots/  retain only…
heartrate.pdf
Bronars.pdf
