### ISSUE TITLE
Ep. 7 Tip backticks appearance error

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#63]
backticks are not appearing in the tip. Figure out how to "escape" so that we can display them properly.

**Comment by ilessing** [comment]
in meeting today solution occured to @torwhite  
> escape all the backticks by pre-ceeding them witth a `\`

**Comment by ilessing** [comment]
fixed with f96b36e9838ae55e436856cffac55d1a0ab2fa53
