### ISSUE TITLE
Ep. 4 reorganization post example simplification

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#64]
We need to take another look at Ep. 4 now that we simplified the paper example and cut down the number of files. We also discussed editing/creating a new challenge that will be more effective about file/directory structure in projects.

**Comment by ilessing** [comment]
in meeting today solution occured to @torwhite  
> escape all the backticks by pre-ceeding them witth a `\`

**Comment by rcurty** [comment]
Completed.
