### ISSUE TITLE
Episode 4 - revise points about filenaming, folder structure of the file system file and directories hierarchy

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#66]
We've reduced the complexity and number of files and directories in our example.

- re-do figure: `04-directory-tree.png`  
- revise text of episode

see also #14

**Comment by ilessing** [comment]
put in excerpt of filesystem screenshot to illustrate the points made about file and directory naming....

> Put each project in its own directory, which is named after the project.  
> Put text documents associated with the project in the doc directory.  
> Put raw data and metadata in the data directory, and files generated during cleanup and analysis in a results directory.  
> Put source for the project’s scripts and programs in the src directory, and programs brought in from elsewhere or compiled locally in the bin directory.
> Name all files to reflect their content or function.
> Additionally, we’d recommend to include README, LICENSE, and CITATION files!

revise and combine the above points.  to make just 4 sections.

**Comment by ilessing** [comment]
in our meeting we agreed to just update the figure for now and do the more involved revision with screenshot excerpts for a later date.

**Comment by ilessing** [comment]
figure revised in commit:  073e5dae which was the urgent part so I will remove the 'urgent' label.

**Comment by ilessing** [comment]
we might want to recommend conforming to ISO {number ????} on file naming conventions.

This standard has recommendations for using hyphens -vs- underscores in file names.

We could have an exercise/challenge for learners to re-name files.

**Comment by brunj7** [comment]
don't forget to remove renv from the project structure

**Comment by rcurty** [comment]
Remove - DataPaper-ReproducibilityWorkshop_files generated when Quarto is rendered
