### ISSUE TITLE
Run-through using Posit Cloud

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#68]
Check flow and possible issues using the cloud version

**Comment by torwhite** [comment]
including Windows, Mac machines etc. Recruit a testing team

**Comment by rcurty** [comment]
I suggest we focus only on the OS differences/testing. We will offer the Jupyter instance. Perhaps add to the teaching notes that instructors should check for variations and adapt lessons accordingly if considering using Posit Cloud.

**Comment by rcurty** [comment]
@torwhite has access RStudio server/Posit Workbench (paid service) and will do a run through of the workshop to see if there are any impediments to learners to complete the workshop if they are using RStudio Server/Posit Workbench.   

We want to know if our workshop is compatible with using a cloud Rstudio rather than a local instance.
