### ISSUE TITLE
missing CSV files. see Example repo issue #4

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#69]
This issue to be closed once the issue in the _Example_ repo is closed.

https://github.com/UCSBCarpentry/Quarto-Project-Example/issues/4

**Comment by rcurty** [comment]
added more explicit mention to the OSF repository in the Readme and teaching notes.

**Comment by ilessing** [comment]
done:  see: 9a0cf1c27b11e0489743170febdb3ea8a7d85621
