### ISSUE TITLE
use a statement in _quarto.yml to avoid path issues

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#70]
suggestion from Paul Harrison from Monash Univ.

> Section 4:
>
> Assuming your R script is in a `code` directory and your data file is in a `data` directory then an example of a relative path to read your data would be: ...

Outside of qmd/rmd documents code will generally run with the project directory as the working directory.

Within qmds, **we emphasized configuring `_quarto.yml` to use the project dir to avoid problems.**

---

We need to investigate how to do this and if it would be effective in reducing _path_ issues.

**Comment by torwhite** [comment]
We have included how to do this in episode 8.

**Comment by rcurty** [comment]
This content is included in Getting Fancy with Code Chunks
How do we use document level settings?. How do we edit project level settings? That's where the yaml at the top of our documents and/or the `_quarto.yml` file that lives in our project root directory comes in.
