### ISSUE TITLE
ep. 7 & 8  old rmarkdown/knitr syntax   - find and update

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#72]
feed back from Paul H. of Monash

> in episodes 7 and 8:  
> There were various places using to old rmarkdown/knitr chunk option syntax.  
> Some incorrect section and challenge numbers.

**Comment by rcurty** [comment]
I believe I have addressed these issues, but I would appreciate another pass.

**Comment by rcurty** [comment]
removed references to rmd.

**Comment by ilessing** [comment]
Episodes have been re-organized since Paul's comment.

| earlier Episode name |   |  new episode name | source file |
| --- | --- |  ----- | --- |
| 7. Adding Code-Generated Plots and Figures |  ==>  | Adding Code to Quarto Documents  |  [05-code-qmd.md](https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/blob/review-revise/_episodes/02-Quarto/05-code-qmd.md) |
| 8. Reproducible & Efficient Methods of Using Code Chunks  |  ==>  | Rendering & Customizing Code Outputs | [06-rendering-code-yaml.md](https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/blob/review-revise/_episodes/02-Quarto/06-rendering-code-yaml.md) |
|   n/a   |     | Advanced Code Chunk Options | [07-advanced-chunk.md](https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/blob/review-revise/_episodes/02-Quarto/07-advanced-chunk.md) |

**Comment by rcurty** [comment]
I updated labels and code chunks options to conform to quarto
