### ISSUE TITLE
New Structure

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#79]
Rethink the structure of the curriculum into three modules:

1) RStudio, Setting up Projects, Project Management/Organization
2) Quarto 
3) Collaboration

Ep. TBD

**Comment by torwhite** [comment]
see https://docs.google.com/spreadsheets/d/1sSBMMUrJgwxOhA4nsM9wABSzPzEJ-toXREcdPVBNRXQ/edit#gid=0

**Comment by brunj7** [comment]
The bucketization has started on this branch: https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/tree/bucketization/_episodes

**Comment by rcurty** [comment]
I believe we can close this issue.

**Comment by rcurty** [comment]
We have completed this reorg.
