### ISSUE TITLE
Bucket 2 - 01 Check Info for Jupyter Instance (UC only) 

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#82]
Does that still stand, or should we update the info line 35 01-basic-rstudio.md

Now, let's open RStudio. You may access it through the Jupyter Hub instance [https://carpentryworkshop.lsit.ucsb.edu](https://carpentryworkshop.lsit.ucsb.edu). After passing authentication, choose `RStudio`. If you want to follow along using your local RStudio, make sure you use IDE version RStudio v2022. 07.1 or later and that it is running [Quarto version 1.2 or above](https://quarto.org/docs/download/prerelease.html). If you need to check that, for RStudio, choose `Help` and `About RStudio`. For the Quarto version checking, type in `packageVersion("quarto")` on the console.

**Comment by kristi-sara** [comment]
New versions, Rstudio 202306, R 4.3.1, Quarto 1.3

**Comment by ilessing** [comment]
this should NOT get added to the incubator version of the workshop.

Let's put a note in the Instructor Notes to omit reference to Jupyter Hub instance if your workshop is not at UCSB

**Comment by rcurty** [comment]
Confirm....same link?
