### ISSUE TITLE
Bucket 2 - 02-quarto-documents episode

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#83]
IMO some content could be moved to 1st ep. on Bucket one: Why Quarto not RMD, real-world applications and the explanation behind the name.

**Comment by ilessing** [comment]
in meeting general agreement this is a good idea

**Comment by brunj7** [comment]
- [x] Remove example (actually already in bucket one)  (see 78f9d21)
- [x] Move Quarto name and Rmd vs qmd (see 3583061 & 67b4114)

**Comment by brunj7** [comment]
ok this is done
