### ISSUE TITLE
Bucket 2 - update screenshots and fix paths to images

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#84]
And update some screenshots

**Comment by ilessing** [comment]
@rcurty to mention specifics some of the screenshots that need updates and then assign to @ilessing for the screenshot creation and updating the repo.

**Comment by rcurty** [comment]
We will need to review all screenshots for RStudio again because there are some changes to the GUI. Code chunks are now executable cells. Preview replaced the Knit/Render button, etc. We might wait to complete this at the very end. This may also require changes in the terminologies we use across the episodes.
<img width="1025" alt="Screen Shot 2023-10-06 at 10 13 04 AM" src="https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/assets/63265343/0fedef7a-c6f7-411a-80b3-0c9d24a4a116">

**Comment by ilessing** [comment]
be aware that if you're working within a project there may be Rstudio/quarto interface differences than when you are working in a quarto project.


|        |    |
| --------- |  --- |
| Knit shows with Rmarkdown | `.rmd` |
| preview shows with plain Markdown  | `.md` |
| render shows with Quarto Markdown | `.qmd` |



be careful to show appropriate screenshot for whatever type of file is current in workshop

**Comment by ilessing** [comment]
see also #90 which might need to be done first so we have up-to-date paths appearing in the screenshots.

**Comment by ilessing** [comment]
some recent commits address this issue:
- 76f3a1ea5a1282cba507d09f182072c9e5739c75
- 7ee43e5390aebb9da7ede03aabf1884435c415c2
- 695d5c798e073a9342e862e6bc92426a3d966c91
- 7ae60a25ea30a3efb3881cefa3a2ef1ec5a2fe6b
- 7f642b3366ab3bbdee39f86e0627b72d5755c111

**Comment by rcurty** [comment]
done

**Comment by ilessing** [comment]
procedure for creating the directory tree figure is outlined/documented in #14
