### ISSUE TITLE
Bucket 2 - 03-writing-styling.md (commit)

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#85]
At the end of the lesson, we ask learners to render and commit. Some learners may be familiar with Git but not necessarily with Git in Rstudio.  I recall some folks feeling lost in that process. Should we walk them through that instead of just asking them to do it themselves? If not on this ep., perhaps 03-setup-versioning on bucket 1?

**Comment by ilessing** [comment]
let's keep mentions of Committing with git out of early episodes.  Instead have learners do _render_ without committing to git repo.

Julien:
> We could take from this one: https://nceas.github.io/scicomp-workshop-collaborative-coding/rstudio.html#creating-a-new-file

**Comment by rcurty** [comment]
Should we replace render with preview based on the GUI change?

No, preview is only for md files in RStudio. Render for qmd and Knit for rmd

**Comment by rcurty** [comment]
Idea. Add content to module 3 - Collaboration/Collaborating via Github. Suggestion: add after line 88.

Have you noticed the blue 'M' flag in the Git Tab before you add your commit message and stage your edits? Do you know what it means? That 'M' indicates tracked files that have been modified. However, there are other flags depending on your interactions with project files—such as deletions, renames, or additions. Additionally, files might be ignored and, therefore,not tracked at all, as illustrated below.

![rstudio-git- icons](https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/assets/63265343/b81bf66a-f41e-4ada-9faa-ebe737cbc1f3)

**Comment by rcurty** [comment]
Add questions/interactive piece
