### ISSUE TITLE
Bucket 2 - 4-plots-figures.md (Data Files)

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#90]
Question:

Should we move all data to the data folder, including the preprocessed-GARP-TSST-data.csv to simplify?

**Comment by rcurty** [comment]
Reorg 
Data (Raw and Pre-processed)
Plots - Report/Figs

**Comment by rcurty** [comment]
Check all paths

**Comment by brunj7** [comment]
Here is a framework we could follow for the file organization: https://www.projecttier.org/tier-protocol/protocol-4-0/

**Comment by ilessing** [comment]
see also issue number 7 in the Project Example repo: [Quarto-Project-Example/issues/7](https://github.com/UCSBCarpentry/Quarto-Project-Example/issues/7) which changes directory structure/hierarchy.

**Comment by torwhite** [comment]
The reorg has been completed for the project example, but we need to review the episodes and fix relative paths and other references as needed. 

New structure: 
/code
/data/raw - mastersheet & bronars
/data/processed - preprocessed
/output - will contain plots
/report - remains the same

**Comment by rcurty** [comment]
Added new screenshots and adjusted the paths accordingly.
