### ISSUE TITLE
follow up on Aariq's suggestion

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#96]
see: https://github.com/carpentries-incubator/Reproducible-Publications-with-RStudio/issues/214

> There's a Manuscript project type currently in pre-release of Quarto that would potentially be really useful for this workshop: https://quarto.org/docs/manuscripts/

**Comment by rcurty** [comment]
add to the teaching notes.
