### ISSUE TITLE
Bucket 3 - 03-Renv Ep

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#97]
For discussion. Consider renaming this episode to "Managing Dependencies" and expand to other options such as 
https://groundhogr.com. Perhaps consider using it instead of renv given the advantages for academics outlined here: https://groundhogr.com/renv. 
This will affect the TBD hands-on component for the episode, and potentially the project example and file structure.

**Comment by ilessing** [comment]
> user can run a script that relies on groundhog by simply executing the code, and the necessary packages will be installed and loaded

Based on this alone I'm in favor of switching to GroundHog.

**Comment by rcurty** [comment]
created a new episode see https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/blob/review-revise/_episodes/03-Collaboration/04-managing-dependencies
